version: '3.7'
services:
 minecraft:
   image: itzg/minecraft-server
   ports:
     - "25565:25565"
   environment:
     EULA: "TRUE"
     MOTD: "§l§cSUP BITCHES§r §nITS 1.18"
     DIFFICULTY: "hard"
     MAX_PLAYERS: 8
     MODE: "survival"
     ENABLE_RCON: "true"
     RCON_PASSWORD: "testing"
     ENABLE_AUTOPAUSE: "TRUE"
   restart: unless-stopped
   tty: true
   stdin_open: true
   volumes:
     # attach a directory relative to the directory containing this compose file
     - ./minecraft-data:/data
   deploy:
     resources:
       limits:
         memory: 1.5G

volumes:
  mc:
  rcon:
