version: '3.7'
services:
 vanilla:
   image: itzg/minecraft-server
   ports:
     - "25565:25565"
   environment:
     EULA: "TRUE"
     MOTD: "SUP §l§cBITCHES§r - it's §n1.18§r time xx"
     DIFFICULTY: "hard"
     MAX_PLAYERS: 10
     MODE: "survival"
     ENABLE_RCON: "true"
     RCON_PASSWORD: "testing"
     ENABLE_AUTOPAUSE: "TRUE"
     DEBUG_MEMORY: "TRUE"
     MAX_MEMORY: "4300M"
     VIEW_DISTANCE: "28"
     SEED: "Geminitayisgood"
   restart: unless-stopped
   tty: true
   stdin_open: true
   volumes:
     # attach a directory relative to the directory containing this compose file
     - ./minecraft-data:/data

volumes:
  mc:
  rcon:
