version: "3.7"
services:
  project_ozone:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      TYPE: "CURSEFORGE"
      VERSION: 1.12.2
      MOTD: "hello §l§cmy dudes§r xx"
      MODE: 'survival'
      DIFFICULTY: "hard"
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      # ENABLE_AUTOPAUSE: "TRUE"
      botania:gardenofglass
      CF_SERVER_MOD: https://www.curseforge.com/minecraft/modpacks/project-ozone-3-a-new-way-forward/download/3590510/file
      DEBUG_MEMORY: "TRUE"
      MAX_MEMORY: "4300M"
      SPAWN_PROTECTION: 0
      ALLOW_FLIGHT: TRUE
      RCON_CMDS_STARTUP:  |-
        /gamerule doFireTick false
      OPS: curly6
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./po3-data:/data

  vanilla:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MOTD: "hello §l§cmy dudes§r - it's §n1.18§r time xx"
      DIFFICULTY: "hard"
      MAX_PLAYERS: 10
      MODE: "survival"
      ENABLE_RCON: "true"
      RCON_PASSWORD: ${RCON_PASSWORD}
      # ENABLE_AUTOPAUSE: "TRUE"
      DEBUG_MEMORY: "TRUE"
      MAX_MEMORY: "4300M"
      VIEW_DISTANCE: "30"
      SEED: "Geminitayisgood"
      RCON_CMDS_STARTUP:  |-
        /gamerule doFireTick false
      OPS: curly6
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data

  backup:
    image: itzg/mc-backup
    # This needs to be set because backups use hostnames
    hostname: minecraftbackup
    # command: /bin/bash
    restart: always
    environment:
      BACKUP_METHOD: restic
      BACKUP_INTERVAL: "3h"
      INITIAL_DELAY: 5
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY}
      RESTIC_FORGET_ARGS: ${RESTIC_FORGET_ARGS}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RCON_PASSWORD: ${RCON_PASSWORD}
      RCON_PORT: 25575
      RCON_HOST: vanilla
    volumes:
      - ./minecraft-data:/data:ro
      - ${HOME}/recover:/recover

volumes:
  mc:
  rcon:
